sudo: false
language: java
jdk:
  - oraclejdk8
env:
  - CC=clang CXX=clang++
script: mvn -B -fae test -Ptest-exclude-native -DlogQuiet
after_success:
  - test $TRAVIS_REPO_SLUG == "v5analytics/visallo" && test $TRAVIS_BRANCH == "master" || test 'echo $TRAVIS_BRANCH | grep -Eq /^release-.*$/' && test $TRAVIS_PULL_REQUEST == "false" && echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>\${env.DEPLOY_USERNAME}</username><password>\${env.DEPLOY_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
  - test -f ~/settings.xml && mvn -B --settings ~/settings.xml -f root/pom.xml deploy
  - test -f ~/settings.xml && mvn -B --settings ~/settings.xml -DskipTests deploy
branches:
  only:
    - master
    - /^release-.*$/
